title: 한희수 포트폴리오 & 블로그
description: CTI Analyst 및 Threat Hunter 한희수의 공간
baseurl: ""
url: "https://crowndaisy76.github.io"
theme: jekyll-theme-cayman

collections:
  tech_posts:
    output: true
    permalink: /tech/:path/
  review_posts:
    output: true
    permalink: /review/:path/